"use client";
import {Captions,Settings,Volume2,X} from "lucide-react";

export default function PlayerSettings({open,onToggle,onClose,rates,playbackRate,availableRates,canControl,onSpeed,audioTracks,subtitleTracks,activeAudio,activeSubtitle,onAudio,onSubtitle,onExternalSubtitleFile,audioNotice,subtitleNotice,subtitleInputError,qualityLabel,activeQuality,qualityOptions=[],selectedQuality="auto",onQualityChange,autoAvailable=false,qualityStatus="not-prepared",hlsError=false,qualitySupported=true}){
 const qualityStateLabel=qualityStatus==="ready"?"Ready":qualityStatus==="preparing"?"Preparing":qualityStatus==="failed"?"Failed":"Not prepared";
 return <div className="absolute right-3 top-3 z-30">
  <button type="button" className="rounded-lg border border-white/15 bg-black/75 p-2 text-white shadow-lg hover:bg-violet-950 focus-visible:outline focus-visible:outline-2 focus-visible:outline-violet-300" aria-label="Player settings" aria-expanded={open} title="Player settings" onClick={onToggle}><Settings size={17}/></button>
  {open&&<section role="dialog" aria-label="Player settings" className="absolute right-0 top-11 max-h-[min(70vh,420px)] w-72 max-w-[calc(100vw-32px)] overflow-y-auto rounded-xl border border-white/15 bg-black/95 p-3 text-sm text-white shadow-2xl backdrop-blur">
   <div className="mb-3 flex items-center"><b className="flex-1">Player settings</b><button type="button" className="rounded p-1 hover:bg-white/10" aria-label="Close player settings" onClick={onClose}><X size={16}/></button></div>
   <section className="border-t border-white/10 py-3"><h3 className="mb-2 flex items-center gap-2 font-semibold"><Settings size={15}/>Playback speed</h3><div className="grid grid-cols-4 gap-1">{rates.map(rate=>{const supported=!availableRates||availableRates.includes(rate);return <button type="button" key={rate} disabled={!canControl||!supported} aria-pressed={Number(playbackRate)===rate} title={!supported?"This player does not support this speed":""} onClick={()=>onSpeed(rate)} className={`rounded px-2 py-1.5 text-xs ${Number(playbackRate)===rate?"bg-violet-600 text-white":"bg-white/5 hover:bg-white/10"} disabled:cursor-not-allowed disabled:opacity-50`}>{rate}x</button>})}</div>{!canControl&&<p className="mt-2 text-xs text-slate-400">The host controls playback speed.</p>}{availableRates&&<p className="mt-2 text-xs text-slate-400">Some speeds are unavailable for this video.</p>}</section>
    <section className="border-t border-white/10 py-3"><h3 className="mb-2 font-semibold">Video quality</h3>{qualitySupported?<div className="space-y-1"><button type="button" disabled={!autoAvailable} aria-pressed={selectedQuality==="auto"} title={!autoAvailable?"Adaptive HLS is unavailable until genuine renditions are prepared and supported here.":"Adaptive bitrate"} onClick={()=>onQualityChange?.("auto")} className={`block w-full rounded px-2 py-1.5 text-left text-xs ${selectedQuality==="auto"?"bg-violet-600/70":"hover:bg-white/10"} disabled:cursor-not-allowed disabled:opacity-50`}>Auto{!autoAvailable&&<span className="float-right text-amber-300">Unavailable</span>}</button>{qualityOptions.map(option=><button type="button" key={option.id} aria-pressed={selectedQuality===option.id} onClick={()=>onQualityChange?.(option.id)} className={`block w-full rounded px-2 py-1.5 text-left text-xs ${selectedQuality===option.id?"bg-violet-600/70":"hover:bg-white/10"}`}>{option.label}</button>)}</div>:<p className="text-xs text-slate-400">YouTube controls quality; manual renditions are not exposed by its player API.</p>}{qualitySupported&&<><p className="mt-2 text-xs text-slate-300">Mode: {selectedQuality==="auto"?`Auto${autoAvailable?"":" unavailable; source fallback"}`:`Manual · ${selectedQuality}`}<br/>Active: {activeQuality||qualityLabel}</p><p className="mt-2 text-xs text-slate-400">{hlsError?"Adaptive streaming failed. The protected source stream is being used.":qualityOptions.length>1?`Renditions: ${qualityStateLabel}. Only generated, available sizes are listed.`:qualityStatus==="preparing"?"Qualities are being prepared by the host.":qualityStatus==="failed"?"Quality preparation failed. The protected source stream remains the fallback.":"No lower-resolution renditions are prepared; the protected source stream is the fallback."}</p></>}</section>
    <section className="border-t border-white/10 py-3"><h3 className="mb-2 flex items-center gap-2 font-semibold"><Volume2 size={15}/>Audio language</h3>{audioTracks.length>0?<div className="space-y-1">{audioTracks.map(track=><button type="button" key={`${track.index}-${track.language}`} aria-pressed={activeAudio===track.index} onClick={()=>onAudio(track.index)} className={`block w-full rounded px-2 py-1.5 text-left text-xs ${activeAudio===track.index?"bg-violet-600/70":"hover:bg-white/10"}`}>{track.label}</button>)}</div>:<p className="text-xs text-slate-400">{audioNotice}</p>}</section>
    <section className="border-t border-white/10 py-3"><h3 className="mb-2 flex items-center gap-2 font-semibold"><Captions size={15}/>Subtitles</h3>{subtitleTracks.length>0&&<div className="mb-2 space-y-1"><button type="button" aria-pressed={activeSubtitle===-1} onClick={()=>onSubtitle(-1)} className={`block w-full rounded px-2 py-1.5 text-left text-xs ${activeSubtitle===-1?"bg-violet-600/70":"hover:bg-white/10"}`}>Off</button>{subtitleTracks.map(track=><button type="button" key={`${track.index}-${track.language}`} aria-pressed={activeSubtitle===track.index} onClick={()=>onSubtitle(track.index)} className={`block w-full rounded px-2 py-1.5 text-left text-xs ${activeSubtitle===track.index?"bg-violet-600/70":"hover:bg-white/10"}`}>{track.label}</button>)}</div>}<p className="mb-2 text-xs text-slate-400">{subtitleNotice}</p>{subtitleInputError&&<p role="alert" className="mb-2 text-xs text-amber-300">{subtitleInputError}</p>}{onExternalSubtitleFile&&<label className="block cursor-pointer rounded border border-white/10 px-2 py-1.5 text-center text-xs text-violet-100 hover:bg-white/5">Add local WebVTT file<input type="file" accept=".vtt,text/vtt" className="sr-only" onChange={event=>{onExternalSubtitleFile(event.target.files?.[0]);event.target.value=""}}/></label>}</section>
  </section>}
 </div>;
}