"use client";
import Link from "next/link";import {useEffect,useState} from "react";import {useRouter} from "next/navigation";
import {Plus,KeyRound,HardDrive,Youtube,Users,Settings,LogOut,CheckCircle2} from "lucide-react";
import Shell from "../../components/Shell";import {Avatar} from "../../components/ui";
import {ytId} from "../../lib/youtube";import {createFirestoreRoom,firestoreRoomError} from "../../lib/firestoreRooms";
import {makeDriveRoomName} from "../../lib/roomNames.cjs";
import DrivePicker from "../../components/DrivePicker";import {connectDrive,disconnectDrive,getDriveStatus} from "../../lib/drive";import {isFirebaseAuthReady} from "../../lib/firebase";import {signOutAll} from "../../lib/auth";import {useAuth} from "../../components/AuthProvider";
import driveOAuthErrors from "../../lib/driveOAuthErrors.cjs";
export default function Dash(){const r=useRouter(),[u,setU]=useState({name:"",email:"",photoURL:null}),[yt,setYt]=useState(""),[msg,setMsg]=useState(""),[driveLinked,setDriveLinked]=useState(false),[driveError,setDriveError]=useState(""),[drivePickerOpen,setDrivePickerOpen]=useState(false),[creating,setCreating]=useState(false);
 const {user,serverSessionReady}=useAuth();useEffect(()=>{setU({name:user?.displayName||user?.email?.split("@")[0]||"Account",email:user?.email||"",photoURL:user?.photoURL||null});if(user)getDriveStatus().then(result=>{setDriveLinked(result.connected);setDriveError(result.error||"")}).catch(error=>setDriveError(error.message))},[user]);
 useEffect(()=>{if(!serverSessionReady||!user)return;const url=new URL(window.location.href),result=url.searchParams.get("drive");if(result==="connected"){setDriveLinked(true);setDrivePickerOpen(true)}else if(result==="setup")setDriveError(driveOAuthErrors.driveOAuthErrorMessage("setup"));else if(result==="error")setDriveError(driveOAuthErrors.driveOAuthErrorMessage(url.searchParams.get("driveError")));if(result){url.searchParams.delete("drive");url.searchParams.delete("driveError");window.history.replaceState(null,"",`${url.pathname}${url.search}${url.hash}`)}},[serverSessionReady,user]);
 const paste=async e=>{e.preventDefault();const id=ytId(yt);if(!id)return setMsg("That isn't a valid YouTube video link.");if(creating)return;setCreating(true);setMsg("");try{const code=await createFirestoreRoom({name:"YouTube room",source:{type:"yt",id,url:yt.trim()}});r.push(`/room/${code}`)}catch(error){setMsg(firestoreRoomError(error));setCreating(false)}};
 const drive=async()=>{if(driveLinked){setDrivePickerOpen(true);return}try{const result=await connectDrive("/dashboard");window.location.assign(result.authorizationUrl)}catch(error){setDriveError(error.message)}};
 const unlinkDrive=async()=>{try{await disconnectDrive();setDriveLinked(false);setDriveError("")}catch(error){setDriveError(error.message)}};
 const browseDrive=async file=>{if(creating)return;setCreating(true);setMsg("");try{const video={...file,type:"drive"},code=await createFirestoreRoom({name:makeDriveRoomName(file.name),source:video});r.push(`/room/${code}`)}catch(error){setMsg(firestoreRoomError(error));setCreating(false)}};
 const out=async()=>{await signOutAll();r.push("/")};
 const A=({href,I,t,d})=><Link href={href} className="card flex items-center gap-3 p-4"><span className="grid h-10 w-10 place-items-center rounded-lg bg-violet-600/30"><I size={18}/></span><span><b className="block text-sm">{t}</b><span className="text-xs text-slate-400">{d}</span></span></Link>;
 return <Shell><div className="mx-auto max-w-3xl space-y-5">
    <div className="card flex items-center gap-4 p-5"><Avatar name={u.name} photoURL={u.photoURL} size="h-14 w-14"/><div className="flex-1"><b>{u.name}</b><p className="text-xs text-slate-400">{u.email}</p><p className="text-xs text-slate-500">{isFirebaseAuthReady?"Signed in via Firebase":"Firebase Authentication unavailable"}</p></div><button onClick={out} className="btn2 !py-1.5"><LogOut size={14}/>Logout</button></div>
  <div className="grid gap-3 sm:grid-cols-2"><A href="/rooms/new" I={Plus} t="Create Room" d="Start a private watch party"/><A href="/join" I={KeyRound} t="Join Room" d="Enter a code or invite link"/><A href="/rooms" I={Users} t="My Rooms" d="Your rooms"/><A href="/settings" I={Settings} t="Settings" d="Profile and preferences"/></div>
  <div className="card flex items-center gap-3 p-4"><HardDrive size={20} className="text-violet-300"/><div className="flex-1"><b className="text-sm">Google Drive</b><p className="text-xs text-slate-400">{driveLinked?"Connected securely":"Connect the room host's Drive once to browse videos."}</p>{driveError&&<p role="alert" className="mt-1 text-xs text-amber-300">{driveError}</p>}</div><button disabled={creating||!user} onClick={drive} className="btn !py-1.5 disabled:opacity-50">{creating?"Working...":driveLinked?"Browse Google Drive":"Connect Google Drive"}</button>{driveLinked&&<button disabled={creating} onClick={unlinkDrive} className="btn2 !py-1.5 disabled:opacity-50">Disconnect</button>}</div>
  <form onSubmit={paste} className="card flex items-center gap-2 p-4"><Youtube size={20} className="text-violet-300"/><input className="input !py-2" placeholder="Paste YouTube Link to start a room" value={yt} onChange={e=>setYt(e.target.value)}/><button disabled={creating} className="btn !py-2 disabled:opacity-50">{creating?"Creating...":"Go"}</button></form>
  {msg&&<p role="alert" className="rounded-lg bg-amber-500/10 p-2 text-xs text-amber-300">{msg}</p>}
  <DrivePicker open={drivePickerOpen} onClose={()=>setDrivePickerOpen(false)} onSelect={browseDrive} returnTo="/dashboard"/>
 </div></Shell>}
